services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=autofix_db
      - POSTGRES_PASSWORD=Autofix$2025@
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/upload    
volumes:
  postgres:
  uploads:
  mongodata: